### ISSUE TITLE
Bluetooth Probes

### ISSUE THREAD

**Issue by W0GER** [njobrien1006/hass_traeger#34]
**Is your feature request related to a problem? Please describe.**

it looks like njobrien1006/hass_traeger (this project) is several commits ahead of sebirdman's upstream repo. Thank you for the commitment to this effort. 

Would it be possible to merge in the following open 2 PR's in sebirdman's project into your fork? 

- [Pull Request 58 Add support for more accessories](https://github.com/sebirdman/hass_traeger/pull/58)  implements the monitoring of the Bluetooth probes.
- [Pull Request 48 Fix availability of Super Smoke](https://github.com/sebirdman/hass_traeger/pull/48)

**Describe the solution you'd like**
A new fork that has all the cool improvements 

**Describe alternatives you've considered**
I opened an issue in sebirdman's project asking to merge the PR's, but have not gotten a response.

**Comment by njobrien1006** [comment]
The associate #48 & #58 have been added along with fixes for the `NumberEntity is overriding deprecated methods on an instance of NumberEntity` changes. Additionally, plenty of other changes for HACS interface for issues and HACS downloading.

Then, there was some discussion a year ago about Linting that never got closure that was rolled in as well.

The release can be found here [2023.05.19.4](https://github.com/njobrien1006/hass_traeger/releases/tag/2023.05.19.4)

I have been using my thread for DEV for a couple of years now and generally contrib upstream but will continue to maintain my fork as long as I own a Traeger, and the API continues to be available.

@noelbundick
@stephenpapierski

**Comment by W0GER** [comment]
Thank you so much!! 

Looks like there has been a lot of activity. We have a big BBQ this weekend, so I'm going to hold off until after that before I install the updates. Super excited to check out what's changed.

**Comment by dandomin** [comment]
Were you able to get btprobes working? I can see probes in my debug logs, but I don't seem to have any entities created for those probes within HA. 

            "acc":[{
                    "channel":"BT1",
                    "btprobe":{
                        "batt":8,
                        "fw":"XX.YY.ZZ",
                        "alarm_fired":0,
                        "get_temp":102,
                        "set_temp":130,
                        "ambient_temp":1162},
                    "type":"btprobe",
                    "uuid":"b81f5e68dff2",
                    "con":1},
                    {"channel":"bt",
                    "hob":{
                        "fw":"01.00.55",
                        "level":0,
                        "get_temp":60,
                        "set_temp":0,
                        "status":0},
                    "type":"hob",
                    "uuid":"8c4b14515b7a",
                    "con":1}],

**Comment by njobrien1006** [comment]
I don't have BT probes so I can't confirm.

But, I can confirm I missed merging sebirdman#58. I have merged it into my dev and Beta-Released as [2023.06.12](https://github.com/njobrien1006/hass_traeger/releases/tag/2023.06.12). Can you check to see if that works for the BT probes?

**Comment by njobrien1006** [comment]
Can you confirm functionality so this can be merged and released as non-beta?
