### ISSUE TITLE
climate.TraegerClimateEntity is using deprecated supported features values which will be removed in HA Core 2025.1

### ISSUE THREAD

**Issue by bakerkj** [njobrien1006/hass_traeger#59]
### System Health details

Core: 2024.1.0
Supervisor: 2023.12.0
Operating: System 11.2
Frontend: 20231208.2

### Checklist

- [ ] I have enabled debug logging for my installation.
- [X] I have filled out the issue template to the best of my ability.
- [X] This issue only contains 1 issue (if you have multiple issues, open one issue for each issue).
- [X] This issue is not a duplicate issue of currently [previous issues](https://github.com/njobrien1006/hass_traeger/issues?q=is%3Aissue+label%3A%22Bug%22+)..

### Describe the issue

Warning from hass_traeger:

```
[homeassistant.helpers.entity] Entity None (<class 'custom_components.traeger.climate.TraegerClimateEntity'>) is using deprecated supported features values which will be removed in HA Core 2025.1. Instead it should use <ClimateEntityFeature.TARGET_TEMPERATURE: 1>,
 please create a bug report at https://github.com/njobrien1006/hass_traeger/issues and reference https://developers.home-assistant.io/blog/2023/12/28/support-feature-magic-numbers-deprecation
```

### Reproduction steps

1. Initially running Home Assistant `2023.12.4` with `hass_traeger` `2023.10.06.01`
2. Upgrade to Home Assistant `2024.1`
3. Observe `home-assistant.log`

### Debug logs

```text
skipped
```

**Comment by njobrien1006** [comment]
Thank you for the report. I'm still on 2023.12.3 and didn't have any of those. 

It would appear they all came with 2023.12.4 on Dec-28-2023. If you'd like you can submit a PR for resolution against DEV branch otherwise, I'll evaluate as time permits.

**Comment by bakerkj** [comment]
Thanks @njobrien1006! I'll let you know if I get a chance to start work on it.

**Comment by njobrien1006** [comment]
I put up a [Beta](https://github.com/njobrien1006/hass_traeger/releases/tag/2024.01.05.Beta). It seems to resolve the issues but need to go through a cook to make sure nothing else broke.

**Comment by tmack8001** [comment]
I didn't see that (this repo or that branch) originally  and added changes to my fork https://github.com/tmack8001/hass_traeger/tree/tmack/update-to-unitoftemp-forked feel free to take any or all the changes if you haven't already done similar yourself.

Mentioned that the other issue already created can be closed.

**Comment by tmack8001** [comment]
Noticed that the minimum HA version wasn't bumped due to the newer HA functionality that is required - so created https://github.com/njobrien1006/hass_traeger/pull/60  to bump that to 2022.11.0 where these constants were added.

**Comment by bakerkj** [comment]
@njobrien1006 thanks for the fix!
