### ISSUE TITLE
reference of temperature units

### ISSUE THREAD

**Issue by doctorkb** [njobrien1006/hass_traeger#67]
### Checklist

- [X] I have filled out the template to the best of my ability.
- [X] This only contains 1 feature request (if you have multiple feature requests, open one feature request for each feature request).
- [X] This issue is not a duplicate feature request of [previous feature requests](https://github.com/njobrien1006/hass_traeger/issues?q=is%3Aissue+label%3A%22Feature+Request%22+).

### Is your feature request related to a problem? Please describe.

Revisiting https://github.com/sebirdman/hass_traeger/issues/51

### Describe the solution you'd like

I'd like the ability to switch between deg C and deg F without changing global settings. (Canada is an odd place -- we use deg C for air temperatures, but deg F for cooking).

Oddly, the "Climate" entity follows my HAss global setting, but the Ambient Temp sensor does not - it's deg F only.

### Describe alternatives you've considered

I'm considering writing my own set of templated cards to do this, but that's suboptimal.

### Additional context

Home Assistant provides for this functionality, if the underlying configuration is there for the entity.  It doesn't appear to be here.

**Comment by njobrien1006** [comment]
There is a small error where the `SensorDeviceClass.TEMPERATURE` is not defined within the sensor entity. This in conjunction with `native_unit_of_measure` and `native_value` provide the ability to switch units of the **SENSOR** entities from the UI.

But for **CLIMATE**, as previously stated in [sebirdman#51](https://github.com/sebirdman/hass_traeger/issues/51#issuecomment-1185697625), the root of your intent to fix the **climate entity unit** is not supported by HA.

**Comment by doctorkb** [comment]
I don't know if something has changed, but the Ecobee climate entity does have the ability to change units... If that helps.

**Comment by njobrien1006** [comment]
> I don't know if something has changed, but the Ecobee climate entity does have the ability to change units... If that helps.

Change Units via what? The system locale setting....yes. Via another means I'm not seeing. Nor do I see it as supported via the [Climate Entity](https://developers.home-assistant.io/docs/core/entity/climate)

This integration follows the Grills setting for the Units. The conversion to C is driven by HA FrontEnd based on Locale Setting with no way of override.

**Comment by doctorkb** [comment]
I could have sworn I saw it on the Climate entity's setting in the Settings section, but I must have been looking at the temperature sensor, as I can't find it now.  I was *certain* I saw it there! I'm sorry!

**Comment by njobrien1006** [comment]
Here is the [Feature Request](https://community.home-assistant.io/t/change-climate-unit-of-measurement/578707).

I've added the raw output of the grill to the attributes in the latest Beta which could be used in templating.

![image](https://github.com/njobrien1006/hass_traeger/assets/59174199/c1c4dcc1-fd1c-411a-b3a8-5d748681a4a3)
